//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collections.Analyzer {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Collections.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CI0001_Title {
            get {
                return ResourceManager.GetString("CI0001_Title", resourceCulture);
            }
        }
        
        internal static string RemoveRedundantCall {
            get {
                return ResourceManager.GetString("RemoveRedundantCall", resourceCulture);
            }
        }
        
        internal static string CI0002_Title {
            get {
                return ResourceManager.GetString("CI0002_Title", resourceCulture);
            }
        }
        
        internal static string CI0003_Title {
            get {
                return ResourceManager.GetString("CI0003_Title", resourceCulture);
            }
        }
        
        internal static string CI0004_Title {
            get {
                return ResourceManager.GetString("CI0004_Title", resourceCulture);
            }
        }
        
        internal static string AddToCharArray {
            get {
                return ResourceManager.GetString("AddToCharArray", resourceCulture);
            }
        }
        
        internal static string ReplaceWithToCharArray {
            get {
                return ResourceManager.GetString("ReplaceWithToCharArray", resourceCulture);
            }
        }
        
        internal static string ReplaceWithCountCall {
            get {
                return ResourceManager.GetString("ReplaceWithCountCall", resourceCulture);
            }
        }
        
        internal static string CI0005_Title {
            get {
                return ResourceManager.GetString("CI0005_Title", resourceCulture);
            }
        }
        
        internal static string CI0006_Title {
            get {
                return ResourceManager.GetString("CI0006_Title", resourceCulture);
            }
        }
        
        internal static string NotEnoughCapacity {
            get {
                return ResourceManager.GetString("NotEnoughCapacity", resourceCulture);
            }
        }
        
        internal static string SetActualCapacity {
            get {
                return ResourceManager.GetString("SetActualCapacity", resourceCulture);
            }
        }
        
        internal static string CI0007_Title {
            get {
                return ResourceManager.GetString("CI0007_Title", resourceCulture);
            }
        }
        
        internal static string ReplaceWithIsEmpty {
            get {
                return ResourceManager.GetString("ReplaceWithIsEmpty", resourceCulture);
            }
        }
        
        internal static string CI0008_Title {
            get {
                return ResourceManager.GetString("CI0008_Title", resourceCulture);
            }
        }
        
        internal static string CI0008_MessageFormat {
            get {
                return ResourceManager.GetString("CI0008_MessageFormat", resourceCulture);
            }
        }
        
        internal static string CI0008_Description {
            get {
                return ResourceManager.GetString("CI0008_Description", resourceCulture);
            }
        }
        
        internal static string CI0008_CodeFixTitle {
            get {
                return ResourceManager.GetString("CI0008_CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string CI0009_Title {
            get {
                return ResourceManager.GetString("CI0009_Title", resourceCulture);
            }
        }
        
        internal static string CI0009_MessageFormat {
            get {
                return ResourceManager.GetString("CI0009_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SetCapacity {
            get {
                return ResourceManager.GetString("SetCapacity", resourceCulture);
            }
        }
        
        internal static string CI0010_Title {
            get {
                return ResourceManager.GetString("CI0010_Title", resourceCulture);
            }
        }
        
        internal static string CI0010_MessageFormat {
            get {
                return ResourceManager.GetString("CI0010_MessageFormat", resourceCulture);
            }
        }
    }
}
